dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}-${BENCH}/${VARIANT}"

script:
  - cd "$dir"
  # Test container build
  - travis_retry docker-compose build
  - docker images
  # Test container run
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "frappe_db" | grep "Up" || exit 1
  - docker-compose ps "frappe_app" | grep "Up" || exit 1
  - docker-compose ps "frappe_web" | grep "Up" || exit 1
  - echo 'Wait until sites and apps database installed (4-5 minutes)' && sleep 300
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "frappe_db" | grep "Up"
  - docker-compose ps "frappe_app" | grep "Up"
  - docker-compose ps "frappe_web" | grep "Up"
  # Test container restart
  - docker-compose down
  - travis_retry docker-compose up -d && sleep 60
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "frappe_db" | grep "Up"
  - docker-compose ps "frappe_app" | grep "Up"
  - docker-compose ps "frappe_web" | grep "Up"

notifications:
  email: false

matrix:
  allow_failures:
    - env: VERSION=develop BENCH=master VARIANT=alpine
    - env: VERSION=develop BENCH=master VARIANT=stretch-slim
    - env: VERSION=develop BENCH=master VARIANT=stretch
    - env: VERSION=12.0 BENCH=master VARIANT=alpine

env: # Environments
  - VERSION=develop BENCH=master VARIANT=alpine
  - VERSION=develop BENCH=master VARIANT=stretch-slim
  - VERSION=develop BENCH=master VARIANT=stretch
  - VERSION=10.x BENCH=master VARIANT=alpine
  - VERSION=10.x BENCH=master VARIANT=stretch-slim
  - VERSION=10.x BENCH=master VARIANT=stretch
  - VERSION=11.1 BENCH=master VARIANT=alpine
  - VERSION=11.1 BENCH=master VARIANT=stretch-slim
  - VERSION=11.1 BENCH=master VARIANT=stretch
  - VERSION=12.0 BENCH=master VARIANT=alpine
  - VERSION=12.0 BENCH=master VARIANT=stretch-slim
  - VERSION=12.0 BENCH=master VARIANT=stretch
