version: "2"

services:
  erpnext_app:
    build: ./
    container_name: erpnext_app
    command: app
    #restart: always
    ports:
      - 8000:8000
    depends_on:
      - erpnextdb
    links:
      - erpnextdb
    environment:
      # Frappe setup
      - FRAPPE_APP_INIT=erpnext
      - FRAPPE_DEFAULT_SITE=${FRAPPE_SITE}
      - FRAPPE_LOGGING=1
      #- ADMIN_USER=Administrator
      - ADMIN_PASSWORD=${FRAPPE_ADMIN_PWD}
      - ENCRYPTION_KEY=${FRAPPE_ENCRYPTION_KEY}
      # Database setup
      - DB_TYPE=mariadb
      - DB_HOST=erpnextdb
      - DB_PORT=3306
      - DB_NAME=${FRAPPE_DB_NAME}
      - DB_PASSWORD=${FRAPPE_DB_PWD}
      - DB_ROOT_PASSWORD=${FRAPPE_DB_ROOT_PWD}
      # Mail setup
      - MAIL_HOST=${FRAPPE_MAIL_HOST}
      - MAIL_PORT=587
      - MAIL_USE_SSL=tls
      - MAIL_LOGIN=${FRAPPE_SMTP_USER}
      - MAIL_PASSWORD=${FRAPPE_SMTP_PWD}
      # Redis setup
      - REDIS_CACHE_HOST=erpnext_redis_cache
      - REDIS_QUEUE_HOST=erpnext_redis_queue
      - REDIS_SOCKETIO_HOST=erpnext_redis_socketio
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /srv/erpnext/frappe/logs:/home/frappe/frappe-bench/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_web:
    image: nginx:alpine
    container_name: erpnext_web
    #restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    volumes_from:
      - erpnext_app
    ports:
      - 80:80
      # If you need SSL connection
      # - '443:443'
    links:
      - erpnext_app
      - erpnext_socketio

  erpnextdb:
    image: mariadb:10
    container_name: erpnextdb
    restart: always
    command: --character_set_client=utf8 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --character-set-client-handshake=FALSE
    environment:
      - MYSQL_ROOT_PASSWORD=${FRAPPE_DB_ROOT_PWD}
      # Following parameters must NOT be set and are only there for documentation (Bench will install DB)
      #- MYSQL_DATABASE=${FRAPPE_DB_NAME}
      #- MYSQL_USER=${FRAPPE_DB_USER}
      #- MYSQL_PASSWORD=${FRAPPE_DB_PWD}
    volumes:
      - /srv/erpnext/db:/var/lib/mysql

  erpnext_scheduler:
    build: ./
    container_name: erpnext_scheduler
    command: scheduler
    #restart: always
    depends_on:
      - erpnext_app
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_worker_default:
    build: ./
    container_name: erpnext_worker_default
    command: worker-default
    #restart: always
    depends_on:
      - erpnext_app
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_worker_long:
    build: ./
    container_name: erpnext_worker_long
    command: worker-long
    #restart: always
    depends_on:
      - erpnext_app
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_worker_short:
    build: ./
    container_name: erpnext_worker_short
    command: worker-short
    #restart: always
    depends_on:
      - erpnext_app
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_socketio:
    build: ./
    container_name: erpnext_socketio
    command: node-socketio
    #restart: always
    ports:
      - 3000:3000
    depends_on:
      - erpnext_app
    volumes:
      - /srv/erpnext/frappe/sites:/home/frappe/frappe-bench/sites
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  erpnext_redis_cache:
    image: redis:alpine
    container_name: erpnext_redis_cache
    #restart: always
    volumes:
      - ./services/erpnext/conf/redis_cache.conf:/etc/conf.d/redis.conf:ro
    command: ["redis-server","/etc/conf.d/redis.conf"]

  erpnext_redis_queue:
    image: redis:alpine
    container_name: erpnext_redis_queue
    #restart: always

  erpnext_redis_socketio:
    image: redis:alpine
    container_name: erpnext_redis_socketio
    #restart: always
